application: kxprxy
version: secureable
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots\.txt

- url: /static
  static_dir: static
  secure: optional

- url: /stylesheets
  static_dir: stylesheets
  secure: optional
  
- url: /main/.*
  script: mirror.app
  secure: optional

- url: /.*
  script: mirror.app
  secure: optional